codecov:
  notify:
    require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # Basic project coverage settings
        target: 70%
        threshold: 2%
        base: auto
        paths:
          - "kapitan/"
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

    patch:
      default:
        # Coverage for new/changed code in PRs
        target: 80%
        threshold: 5%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: true

    changes:
      default:
        # Track coverage changes
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true

ignore:
  - "tests/**"
  - "**/*_test.py"
  - "**/test_*.py"
  - "setup.py"
  - "docs/**"
  - "examples/**"

flags:
  unittests:
    paths:
      - kapitan/
    carryforward: true
