#!/usr/bin/env python3

# Copyright 2019 The Kapitan Authors
# SPDX-FileCopyrightText: 2020 The Kapitan Authors <kapitan-admins@googlegroups.com>
#
# SPDX-License-Identifier: Apache-2.0

"""External input tests refactored for pytest."""

import os
import random
import string
import subprocess

import pytest

from kapitan.inputs.external import External
from kapitan.inventory.model.input_types import KapitanInputTypeExternalConfig
from tests.test_helpers import CompileTestHelper


class TestExternalInput:
    """Test external input compilation."""

    def test_compile(self, isolated_test_resources, temp_dir):
        """Test compilation with external input."""
        output_path = os.path.join(temp_dir, "output")
        helper = CompileTestHelper(isolated_test_resources)
        helper.compile_with_args(["kapitan", "compile", "--output-path", output_path, "-t", "external-test"])

        output_file = os.path.join(output_path, "compiled", "external-test", "test.md")
        assert os.path.isfile(output_file)

    def test_compile_file(self, temp_dir):
        r"""Test setting of args, env_vars and ${compiled_target_dir} substitution."""
        external_script_content = """
        #!/usr/bin/env bash
        set -ex

        name=$1
        compiled_target_dir=$2

        echo "test-${NAME}" > "${compiled_target_dir}/${name}"
        """
        compile_path = os.path.join(temp_dir, "compile")
        script_dir = os.path.join(temp_dir, "scripts")
        os.makedirs(compile_path)
        os.makedirs(script_dir)

        external_script_file_path = os.path.join(script_dir, "script.sh")
        with open(external_script_file_path, "w") as f:
            f.write(external_script_content)

        search_paths = [external_script_file_path]
        ref_controller = None
        external_compiler = External(compile_path, search_paths, ref_controller, "test", None)

        letters = string.ascii_lowercase
        name = "".join(random.choice(letters) for i in range(8))
        config = KapitanInputTypeExternalConfig(
            input_paths=[external_script_file_path],
            output_path=compile_path,
            env_vars={"NAME": name},
            args=[name, r"${compiled_target_dir}"],
        )

        # Test that non-executable script fails
        with pytest.raises(ValueError) as exc_info:
            external_compiler.compile_file(config, external_script_file_path, compile_path)

        assert "Executing external input with command" in str(exc_info.value)
        assert "failed" in str(exc_info.value)
        assert "Permission denied" in str(exc_info.value)

        # Make file executable so there's no failure
        subprocess.check_call(["chmod", "+x", external_script_file_path])
        external_compiler.compile_file(config, external_script_file_path, compile_path)

        generated_file = os.path.join(compile_path, name)
        assert os.path.isfile(generated_file), f"File {generated_file} should be generated by compile_file"

        with open(generated_file, "r") as f:
            generated_file_content = f.readlines()[0]

        expected_content = f"test-{name}\n"
        assert generated_file_content == expected_content, "Correct content should be written to file"
