parameters:

  type: terraform

  kapitan:
    vars:
      target: ${_reclass_:name:full}

    compile:

      - output_path: terraform
        output_type: json
        prune: false
        input_paths:
          - templates/terraform/main.jsonnet
        input_type: jsonnet

      - output_path: scripts
        input_type: jinja2
        input_paths:
          - templates/scripts/
