name: Feature Request
description: Request a new functionality
title: "[feat]: "
labels: ["feature"]
body:
  # information
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  # feature description
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature
      description: |
        A clear and concise description of what the feature request is.
        Please make proposals, how you would use this feature (syntax).
      placeholder: Tell us what you want to see in the project!
    validations:
      required: true
  # additional context
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the feature here.
      placeholder: Anything that might help us understanding your feature request...
