kind: Deployment
metadata:
  name: nginx
  namespace: minikube-nginx
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1:15.8
          name: nginx
          ports:
            - containerPort: 80
