########################################
# Classes to include in this target
########################################
classes:
  - common

########################################
# override variables defined in any of
# the classes above
########################################
parameters:
  name: project2
  main_region: europe-west2
  main_zone: europe-west2-a

  resources:

    container:

      cluster1:
        min_master_version: 1.9.2-gke.1
        node_version: 1.9.2-gke.1
        pools:
          pool1a:
            disk_size_gb: 100
            image_type: COS
            machine_type: n1-standard-2
            node_count: 3

      cluster2:
        min_master_version: 1.9.2-gke.1
        node_version: 1.9.2-gke.1
        pools:
          pool2a:
            disk_size_gb: 100
            image_type: COS
            machine_type: n1-standard-2
            node_count: 3
