# This file is here as an example of how a multiline secret would look like in raw form.
var1:
  password: X0pNcTlTWXhXNXpmbHJITURtcElLaUtfLWJrc3FNeFZERTFudi1mTEVKNA==

var2:
  password_sha256: NWIwNThlNGQ2ZTNiNGE4YWQzOWYwZDVhYTE3YTk5NGIwOWRiOGYwMzJmMDNjMzIyMmIyZjU5N2FkYzRiZDUyYQ==
