# ------------------------------------------------
# Path filters for test-build-publish.yml
# ------------------------------------------------

docs:
  - 'docs/**'
  - '.github/workflows/documentation.yml'
  - 'mkdocs.yml'
  - 'CNAME'

code:
  - '**'
  - '!docs/**'
  - '!mkdocs.yml'
  - '!CNAME'
  - '!.github/filters/**'
  - '!.github/workflows/documentation.yml'
  - '!.github/workflows/housekeeping.yml'
  - '!.github/workflows/makefile-test.yml'
  - '!.github/workflows/pex-build-upload.yml'
  - '!.github/workflows/python-pypi-publish-dev.yml'
  - '!.github/workflows/python-pypi-publish.yml'
