---
# Filters used by GitHub Actions path-filter jobs.
# Changes to these paths should trigger performance benchmarks.

benchmark:
  - "kapitan/inventory/**"
  - "kapitan/inputs/**"
  - "kapitan/targets.py"
  - "kapitan/resources.py"
  - "kapitan/cached.py"
  - "kapitan/refs/**"
  - "tests/test_compile_performance.py"
  - "tests/test_resources/inventory/performance/**"
  - ".github/workflows/benchmark.yml"
  - ".github/filters/filters.yml"
  - "pyproject.toml"

# ------------------------------------------------
# Path filters for test-build-publish.yml
# ------------------------------------------------

docs:
  - 'docs/**'
  - '.github/workflows/documentation.yml'
  - 'mkdocs.yml'
  - 'CNAME'

code:
  - '**'
  - '!docs/**'
  - '!mkdocs.yml'
  - '!CNAME'
  - '!.github/filters/**'
  - '!.github/workflows/documentation.yml'
  - '!.github/workflows/housekeeping.yml'
  - '!.github/workflows/makefile-test.yml'
  - '!.github/workflows/pex-build-upload.yml'
  - '!.github/workflows/pr-auto-label.yml'
  - '!.github/workflows/python-pypi-publish-dev.yml'
  - '!.github/workflows/python-pypi-publish.yml'
