apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: ?{vaultkv:targets/minikube-mysql/mysql/vault_secret:20a9f0df}
kind: Secret
metadata:
  annotations: {}
  labels:
    name: example-mysql
  name: example-mysql
  namespace: minikube-mysql
type: Opaque
