apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: nginx
  name: nginx
  namespace: minikube-nginx-jsonnet
spec:
  loadBalancerSourceRanges: []
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: nginx
  type: NodePort
