apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: minikube-nginx-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.5.1
    helm.sh/chart: ingress-nginx-4.4.0
  name: minikube-nginx-helm-ingress-nginx
  namespace: minikube-nginx-helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minikube-nginx-helm-ingress-nginx
subjects:
  - kind: ServiceAccount
    name: minikube-nginx-helm-ingress-nginx
    namespace: minikube-nginx-helm
