apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: glob_instance-jsonnet
  name: glob_instance-jsonnet
  namespace: all-glob
spec:
  clusterIP: None
  loadBalancerSourceRanges: []
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    name: glob_instance
  type: ClusterIP
