apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: ?{base64:targets/all-glob/mysql/password:3192c15c}
  MYSQL_ROOT_PASSWORD_SHA256: ?{base64:targets/all-glob/mysql/password_sha256:a18bc263}
kind: Secret
metadata:
  annotations: {}
  labels:
    name: glob_instance
  name: glob_instance
  namespace: all-glob
type: Opaque
