apiVersion: v1
kind: Service
metadata:
  labels:
    name: glob_instance
  name: glob_instance
  namespace: all-glob
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    name: glob_instance
  type: ClusterIP
