parameters:
  postgres:
    name: db
    component: db
    instance: postgres
    version: "11.0"

  kapitan:
    compile:
      - output_path: ./labels
        input_type: jinja2
        input_paths:
          - components/labels/service.yml
