---
name: Benchmark Master

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  benchmark:
    name: Benchmark Master
    uses: ./.github/workflows/benchmark-reusable.yml
    with:
      compare-baseline: false
      fail-on-alert: false
      comment-on-alert: false
      push-charts: true
      save-baseline: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
