---
name: PEX Build and Upload

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Upload Python Package
    types:
      - completed

jobs:
  pex_build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: |
            3.10
            3.11
            3.12
            3.13
            3.14
      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      - name: Install libraries dependencies
        run: |
          uv pip compile \
            --all-extras \
            --format=requirements.txt \
            --output-file=requirements.txt \
            pyproject.toml
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: 1.17
      - name: Build Pex
        run: |-
          mkdir -p dist
          uvx pex '.[gojsonnet,omegaconf,reclass-rs]' -r requirements.txt \
            --python-shebang='#!/usr/bin/env python3' \
            --python=python3.11 \
            --python=python3.10 \
            --python=python3.12 \
            --python=python3.13 \
            --python=python3.14 \
            -m kapitan \
            -o dist/kapitan.linux-x86_64.pex
          dist/kapitan.linux-x86_64.pex --help

      - name: Add linux-x86_64 pex to assets
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/kapitan.linux-x86_64.pex
