---
classes:
  - common
  - features.exports
  - nested.child
  - relative.sibling

parameters:
  environment: staging
  child_override: overridden

  kapitan:
    compile:
      - input_type: jinja2
        input_paths:
          - templates/output.j2
        output_path: .
        output_type: yaml
        suffix_remove: true
