---
classes:
  - common
  - features.interpolation
  - features.dicts

parameters:
  kapitan:
    compile:
      - input_type: jinja2
        input_paths:
          - templates/output.yaml.j2
        output_path: .
        output_type: yaml
        suffix_remove: true
